#!/usr/bin/perl

use strict;
use warnings;

print "Content-Type: text/html\n\n";
print "<html>\n";
print "<head><title>Current Time - Perl</title></head>\n";
print "<body>\n";
print "<h1>Current Time (Perl Version)</h1>\n";
print "<p>The current time is: " . localtime() . "</p>\n";
print "<p>Generated by Perl CGI script</p>\n";
print "</body>\n";
print "</html>\n";
